---
- name: Resolve Wazuh server IP from inventory
  ansible.builtin.set_fact:
    wazuh_server_ip: >-
      {{ hostvars[
           groups['all']
           | select('match', '.*wazuh-server.*')
           | list
           | first
         ]['ansible_host'] }}
  when: wazuh_server_ip is not defined

- name: Fail if Wazuh server IP could not be resolved
  ansible.builtin.fail:
    msg: >
      Could not resolve wazuh_server_ip automatically.
      Set it manually in role_vars: wazuh_server_ip: "10.x.10.10"
  when: wazuh_server_ip is not defined

- name: Install required packages
  ansible.builtin.apt:
    name:
      - curl
      - gnupg
      - apt-transport-https
    state: present
    update_cache: yes

- name: Download Wazuh agent package
  ansible.builtin.get_url:
    url: https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.14.3-1_amd64.deb
    dest: /tmp/wazuh-agent_4.14.3-1_amd64.deb
    mode: '0644'

- name: Install Wazuh agent package
  ansible.builtin.command: >
    dpkg -i /tmp/wazuh-agent_4.14.3-1_amd64.deb
  environment:
    WAZUH_MANAGER: "{{ wazuh_server_ip }}"
    WAZUH_AGENT_NAME: "{{ wazuh_agent_name | default('ludus-agent') }}"

- name: Ensure Wazuh agent is enabled and running
  ansible.builtin.systemd:
    name: wazuh-agent
    state: started
    enabled: true
    daemon_reload: yes